<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Faker\Factory as Faker;
use Illuminate\Support\Arr;
use App\Models\Login;
use App\Models\Divisi;
use App\Models\Periode;
use App\Models\Laporan;
use App\Models\Folder;
use App\Models\File;
use App\Models\Area;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {

        // Inisialisasi Data Faker
        $faker = Faker::create('id_ID');
        // =================================================================================================
        // =================================================================================================
        // Generate Data Divisi
        $array_divisi = [
            'IT',
            'HRD',
            'Finance',
            'Purchasing',
            'Administrative',
            'Heavy-Equipment',
            'Tambang',
            'Operational',
            'Audit',
            'Produksi',
            'Audit',
            'WTP',
            'Boiler',
            'Electric & Instrumen',
            'Mechanic',
            'Pabrikasi',
            'HSE',
            'Housekeeping',
            'Maintenance Office',
            'Security',
            'Warehouse',
            'Sipil',
            'Logistik',
            'Translator',
            'Labolatory',
            'Head Office - Jakarta',
        ];

        foreach ($array_divisi as $rr) {
            $divisi = new Divisi;
            $divisi_nama = $rr;
            $save_divisi = $divisi->create([
                'divisi_nama' => $divisi_nama,
                'divisi_keterangan' => $divisi_nama,
                'created_at' => now(),
                'updated_at' => now()
            ]);
            $save_divisi->save();
        }

        $array_area = [
            'Crusher Baru',
            'Crusher Lama to Mixer',
            'J2 Tank',
            'Thickener',
            'Vaccum Filter',
            'V-20109A dan Desalter',
            'Tanki 6',
            'Tanki 7',
            'Distilasi',
            'Packing',
            'Lab',
            'Boiler',
            'WTP',
            'RO Pabrik',
            'Genset',
            'Electric',
            'Gudang',
            'Gudang Gas',
            'Workshop',
            'Stockpile Lama',
            'Stockpile Baru',
            '304',
            '305',
            'Mixer',
            'Office',
            '202',
            '201',
            '306',
            'Batching Plant',
        ];

        foreach ($array_area as $areas) {
            $area_nama = $areas;
            Area::create([
                'areakerja_lokasi' => $area_nama,
                'areakerja_kode' => $area_nama,
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }

        // =================================================================================================
        // Generate Data Periode
        $tahun_periode = "2024";
        $array_bulan = [
            'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
        ];
        $iter = 1;

        foreach ($array_bulan as $rr) {
            $periode = new Periode;
            $save_divisi = $periode->create([
                'periode_bulan_int' => $iter++,
                'periode_tahun' => $tahun_periode,
                'periode_bulan' => $rr,
                'created_at' => now(),
                'updated_at' => now()
            ]);
            $save_divisi->save();
        }

        // =================================================================================================
        // =================================================================================================

        // Get Data Divisi
        $divisi_get = Divisi::all();

        // =================================================================================================
        // =================================================================================================


        $employees = [
            ["Nama" => "Sudarman", "Div" => "Manager Pabrik", "Nik/ID" => "KPA00128", "Jabatan" => 10],
            ["Nama" => "Ujang Jaenudin", "Div" => "Super Attedant I", "Nik/ID" => "KPA00153", "Jabatan" => 10],
            ["Nama" => "Mugiono", "Div" => "SPV Grup C", "Nik/ID" => "KPA00087", "Jabatan" => 10],
            ["Nama" => "Akhmad Maftukhin", "Div" => "SPV Grub A", "Nik/ID" => "KPA00154", "Jabatan" => 10],
            ["Nama" => "Muh.Habib Muhanny", "Div" => "SPV Grub B", "Nik/ID" => "KPA00165", "Jabatan" => 10],
            ["Nama" => "Tan Ayong", "Div" => "SPV Daily", "Nik/ID" => "KPA00358", "Jabatan" => 10],
            ["Nama" => "Vacancy", "Div" => "Super Attedant II", "Nik/ID" => "KPA99999", "Jabatan" => 10],
            ["Nama" => "Hikmayani", "Div" => "Head Laboratory", "Nik/ID" => "KPA01122", "Jabatan" => 25],
            ["Nama" => "Fajarudin", "Div" => "Leader Grub A", "Nik/ID" => "KPA00077", "Jabatan" => 25],
            ["Nama" => "Lm.Raif Alfaizhar F.", "Div" => "Leader Grub B", "Nik/ID" => "KPA00185", "Jabatan" => 25],
            ["Nama" => "Agung Atmajaya", "Div" => "Leader Grub C", "Nik/ID" => "KPA00227", "Jabatan" => 25],
            ["Nama" => "Haryudi", "Div" => "Head Utillity", "Nik/ID" => "KPA00213", "Jabatan" => 12],
            ["Nama" => "Michael Doni T.H", "Div" => "Head Boiler", "Nik/ID" => "KPA00022", "Jabatan" => 13],
            ["Nama" => "La Tondi", "Div" => "Leader Grub A", "Nik/ID" => "KPA00157", "Jabatan" => 13],
            ["Nama" => "La Dino", "Div" => "Leader Grub B", "Nik/ID" => "KPA00166", "Jabatan" => 13],
            ["Nama" => "Agus Fatmanto", "Div" => "Leader Grub C", "Nik/ID" => "KPA00203", "Jabatan" => 13],
            ["Nama" => "Fahrosiudin", "Div" => "Leader Grub D", "Nik/ID" => "KPA00342", "Jabatan" => 13],
            ["Nama" => "Rukman", "Div" => "Head Electic & Instrument", "Nik/ID" => "KPA00125", "Jabatan" => 14],
            ["Nama" => "Frans Denny Manurung", "Div" => "Head Mekanik & Pabrikasi", "Nik/ID" => "KPA00023", "Jabatan" => 15],
            ["Nama" => "Suminta", "Div" => "Supervisor Pabrikasi", "Nik/ID" => "KPA00064", "Jabatan" => 16],

            // Data tambahan dari gambar terbaru
            ["Nama" => "Jimmy Khustin Chandra", "Div" => "PJ Gudang & Admin", "Nik/ID" => "KPA00005", "Jabatan" => 8],
            ["Nama" => "Suharni", "Div" => "Admin Umum", "Nik/ID" => "KPA00238", "Jabatan" => 5],
            ["Nama" => "Irma Wati", "Div" => "Finance", "Nik/ID" => "KPA00243", "Jabatan" => 3],
            ["Nama" => "Sarfin Ardi", "Div" => "Quality Control Bahan Baku/Timbangan", "Nik/ID" => "KPA00220", "Jabatan" => 7],
            ["Nama" => "Andri Sepriadi", "Div" => "Head Purchasing", "Nik/ID" => "KPA00054", "Jabatan" => 4],
            ["Nama" => "Basuki", "Div" => "Kepala Gudang", "Nik/ID" => "KPA00012", "Jabatan" => 21],
            ["Nama" => "Tri Hartanto", "Div" => "Kepala Workshop dan Heavy-Equipment", "Nik/ID" => "KPA00053", "Jabatan" => 6],
            ["Nama" => "Rosmawati", "Div" => "Translator", "Nik/ID" => "KPA00322", "Jabatan" => 24],
            ["Nama" => "Erta Hermawan", "Div" => "Arsitek Sipil", "Nik/ID" => "KPA00190", "Jabatan" => 22],
            ["Nama" => "Hendri Ahmad Z.", "Div" => "Logistik", "Nik/ID" => "KPA00388", "Jabatan" => 23],

            // Data tambahan gambar kedua
            ["Nama" => "Andi S.Ginting", "Div" => "Human Capital & GA", "Nik/ID" => "KPA00152", "Jabatan" => 2],
            ["Nama" => "La Ode Amyn Nadjin", "Div" => "HRD", "Nik/ID" => "KPA00007", "Jabatan" => 2],
            ["Nama" => "Sri Titi Wahyu Ningsi", "Div" => "HRD", "Nik/ID" => "KPA00135", "Jabatan" => 2],
            ["Nama" => "Jarot Priyono", "Div" => "Manager HSE", "Nik/ID" => "KPA00126", "Jabatan" => 17],
            ["Nama" => "Trisnawati Rawu", "Div" => "HSE", "Nik/ID" => "KPA00008", "Jabatan" => 17],
            ["Nama" => "Anang Nugroho", "Div" => "Training HSE", "Nik/ID" => "KPA00132", "Jabatan" => 17],
            ["Nama" => "Wahyu Nur Susilo", "Div" => "Manager IT", "Nik/ID" => "KPA00122", "Jabatan" => 1],
            ["Nama" => "Muh.Fathurrahman", "Div" => "IT", "Nik/ID" => "KPA00324", "Jabatan" => 1],
            ["Nama" => "Sutrisno", "Div" => "Maintenance Office", "Nik/ID" => "KPA00017", "Jabatan" => 19],
            ["Nama" => "Yuli Supamrih", "Div" => "Head Housekeeping", "Nik/ID" => "KPA00025", "Jabatan" => 18],
            ["Nama" => "Buntoro", "Div" => "Head Security", "Nik/ID" => "KPA00034", "Jabatan" => 20],
        ];

        foreach ($employees as $insert) {
            $cari_divisi = $divisi_get->where('id', $insert["Jabatan"])->first();
            $div = $insert['Div'];
            if (in_array($div,
            ["Human Capital & GA",
            "PJ Gudang & Admin",
            "Manager Pabrik",
            "Arsitek Sipil",
            "Head Mekanik & Pabrikasi",
            "Kepala Gudang",
            "Kepala Workshop dan Heavy-Equipment",
            "Head Electic & Instrument",
            "Head Purchasing",
            "Head Laboratory",
            "Head Utillity",
            "Head Housekeeping",
            "Head Security",
            "Manager IT",
            "Manager HSE",
            "Maintenance Office",]
            )) {
                $role = 'pj';
            } else {
                $role = 'sp';
            }
            $token = Str::random(16);
            $login_no_karyawan = $insert["Nik/ID"];
            $hashPassword = Hash::make('12345', [
                'rounds' => 12,
            ]);
            $hashToken = Hash::make($token, [
                'rounds' => 12,
            ]);
            Login::create([
                'login_nama' => $insert["Nama"],
                'login_username' => $login_no_karyawan,
                'login_password' => $hashPassword,
                'login_no_karyawan' => $login_no_karyawan,
                'login_email' => null,
                'login_telepon' => null,
                'login_token' => $hashToken,
                'login_level' => $role,
                'login_jabatan' => $insert["Div"],
                'login_status' => "verified",
                'divisi_id' => intval($insert["Jabatan"]),
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }

        $ambil_divisi = Divisi::all();
        foreach ($ambil_divisi as $divs) {
            $folder_keterangan = "Folder Dokumen dan Laporan Divisi " . $divs->divisi_nama;
            $folder_kode = "KPA-DOC-00" . $divs->id;
            $folder_status = "AKTIF";
            Folder::create([
                'folder_nama' => $divs->divisi_nama,
                'folder_keterangan' => $folder_keterangan,
                'folder_kode' => $folder_kode,
                'folder_status' => $folder_status,
                'divisi_id' => $divs->id,
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }

        // =================================================================================================
        // =================================================================================================
        //         DB::insert("
        //             INSERT INTO `laporan` (`id`, `laporan_rencana_kerja`, `laporan_jumlah_hari`, `laporan_presentasi_pencapaian`, `laporan_keterangan`, `laporan_status`, `area_id`, `divisi_id`, `login_id`, `periode_id`, `created_at`, `updated_at`) VALUES
        // (39, 'Pencocokan daftar makan di kantin (antara Housekeeping dan HRD)', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Kegiatan Rutin Setiap Hari', 'PENDING', NULL, 2, 37, 11, '2024-11-01 11:33:54', '2024-10-28 11:33:54'),
        // (40, 'Pengaturan jadwal supir untuk rutinitas penjemputan dan pengantaran', '\"[false,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true]\"', 80, 'Rutinitas tiap hari', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:22:07', '2024-10-28 08:22:07'),
        // (42, 'Laporan Absensi TKA bulan Oktober 2024', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Rutinitas Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:00:55', '2024-10-28 08:00:55'),
        // (44, 'Pembuatan Database APD', NULL, 80, 'Rutinitas Tiap Hari', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:08:14', '2024-10-28 08:08:14'),
        // (45, 'Pembuatan Database Deposit Pengambilan APD', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Rutinitas tiap hari', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:08:53', '2024-10-28 08:08:53'),
        // (46, 'Upah Helper Geologist Periode 16 - 31  Oktober 2024', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Laporan Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:39:16', '2024-10-28 08:39:16'),
        // (47, 'Laporan Tagihan Makan Kantin Daffa  Periode 16-31 Oktober', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:40:45', '2024-10-28 08:40:45'),
        // (48, 'Laporan Absensi dan Upah Choirin Periode 16-31 Oktober 2024', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:51:30', '2024-10-28 08:51:30'),
        // (49, 'Laporan Data TKI Harian Bulan November 2024', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 60, 'Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:42:37', '2024-10-28 08:42:37'),
        // (50, 'Laporan Insentif dan Lembur bulan November 2024', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 60, 'Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:43:16', '2024-10-28 08:43:16'),
        // (51, 'Pendaftaran BPJS Kes dan BPJS Ketenagakerjaan Karyawam', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 50, 'Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-01 08:44:29', '2024-10-28 08:44:29'),
        // (52, 'Setting HT HYT PD-568 Untuk Produksi', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-28 09:04:20', '2024-10-31 01:43:27'),
        // (53, 'Reboot Camera CCTV Parkiran 2 Unit Cam#1 dan Cam#2', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-28 09:05:09', '2024-10-31 01:43:42'),
        // (54, 'Packing Modem LNS 2 (80) untuk dikirim ke Jakarta (Kantor Pusat)', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-28 09:05:48', '2024-10-31 01:44:17'),
        // (55, 'Fixing Bug pada Komponen Navbar dan Finishing Upload Database pada Aplikasi Management Report', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-28 09:06:33', '2024-10-31 01:44:32'),
        // (56, 'Perbaikan Bug pada Navigasi Daftar Divisi pada Komponen Navbar untuk Aplikasi Management Report', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-26 09:07:20', '2024-10-31 01:44:44'),
        // (57, 'Finishing Database untuk Data Produk dan Upload hasil Bug Fixing pada Website Indoasphalt.com', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-27 09:08:26', '2024-10-31 01:44:59'),
        // (58, 'Mengubah Struktur Database untuk pembuatan Tabel Produk pada Website Indoasphalt.com', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-25 09:08:58', '2024-10-31 01:45:15'),
        // (59, 'Finishing dan Proses Pembuatan Komponen Modal \"Ubah Data\" pada Halaman Index Laporan untuk menambahkan fungsi mengubah Laporan yang telah diupload di Aplikasi Management Report', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-23 09:11:29', '2024-10-31 01:45:40'),
        // (60, 'Membantu Setting dan Konfigurasi HT Baofeng Tipe UV-82 Milik Pribadi dari Pak Wiji (Produksi)', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-21 09:14:09', '2024-10-31 01:45:58'),
        // (61, 'Ganti Mouse Komputer Timbangan yang telah Rusak, diganti dengan Mouse Baru', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-21 09:14:53', '2024-10-31 01:47:30'),
        // (62, 'Menyelesaikan Tampilan \"Homepage\" dari Website Indoasphalt.com', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-21 09:15:55', '2024-10-31 01:47:55'),
        // (63, 'Lanjut memindahkan Access Point Wifi dari Panel dibawah Tower Jaringan Baru ke dalam Ruang Kerja Pak Sudarman di Control Room Lt.1', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-22 05:05:49', '2024-10-31 05:05:49'),
        // (64, 'Perbaikan Halaman Login yang error ketika User salah mengetik Password pada Aplikasi Management Report', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-22 09:25:39', '2024-10-31 01:48:45'),
        // (65, '- Laporan Invoice BPJS Ketenagakerjaan dan BPJS Kesehatan Periode November 2024', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-04 00:40:16', '2024-10-30 00:40:16'),
        // (66, '- Laporan Insentif PKL Bulan November 2024', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-04 00:41:12', '2024-10-30 00:41:12'),
        // (67, '- Upah Helper Geologist Periode 1-15 November 2024', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Laporan Rutin', 'PENDING', NULL, 2, 37, 11, '2024-11-16 00:42:38', '2024-10-30 00:42:38'),
        // (68, '- Laporan Tagihan Makan Kantin Daffa Periode 1-15 November 2024', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Laporan Rutin', 'PENDING', NULL, 2, 37, 11, '2024-11-16 00:43:28', '2024-10-30 00:43:28'),
        // (69, '- Laporan Absensi dan Upah Choirin Periode 1-15 November 2024', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 50, 'Laporan Rutin', 'PENDING', NULL, 2, 37, 11, '2024-11-16 00:44:33', '2024-10-30 00:44:33'),
        // (70, 'Cut Off Gaji Bulan Oktober 2024', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Laporan Rutin', 'PENDING', NULL, 2, 37, 11, '2024-11-18 00:45:40', '2024-10-30 00:45:40'),
        // (71, 'Cut Off Gaji Harian Bulan Oktober 2024', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Laporan Rutin', 'PENDING', NULL, 2, 37, 11, '2024-11-18 00:46:32', '2024-10-30 00:46:32'),
        // (72, 'Pengecekan Proses Klaim BPJS Ketenagakerjaan', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Laporan Rutin Awal Bulan', 'PENDING', NULL, 2, 37, 11, '2024-11-04 00:47:32', '2024-10-30 00:47:32'),
        // (73, 'Pembuatan Database Karyawan Sakit, Ijin, Alpa dan Cuti', '\"[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 80, 'Laporan Rutin', 'PENDING', NULL, 2, 37, 11, '2024-11-11 00:48:34', '2024-10-30 00:48:34'),
        // (74, 'Sosialisasi  Pemotongan Deposit Seragam Indoasphalt', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 50, 'Laporan Rutin', 'PENDING', NULL, 2, 37, 11, '2024-11-15 00:49:34', '2024-10-30 00:49:34'),
        // (75, 'Pengajuan Riksa Uji : Crusher, Hydrant, Instalasi Pemadam Kebakaran, 1 Unit Excavator, I Unit Fotklift, Crane, 2 Unit Loader, Bachoe Loader, Instalasi Listrik Office dan Instalasi Listrik di Pabrik.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 75, 'Laporan Rutin', 'PENDING', NULL, 2, 37, 11, '2024-11-18 00:51:18', '2024-10-30 00:51:18'),
        // (76, 'Reset Counter Pemakaian Bulanan Kuota User, Mangle, Interfaces dan Queues-Tree pada Jaringan MikroTik Ecoasphalt', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 04:50:15', '2024-10-31 04:50:15'),
        // (80, 'Konfigurasi CCTV untuk area Timbangan telah dilakukan, dengan alokasi IP address: 164', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:45:05', '2024-10-31 01:52:10'),
        // (81, 'Konfigurasi CCTV untuk area 301 telah dilakukan, dengan alokasi IP address: 198', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:45:32', '2024-10-31 01:52:31'),
        // (82, 'Pengecekkan Rutin CCTV Area Office dan Pabrik', '\"[false,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true]\"', 100, 'Rutin setiap hari', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 06:01:41', '2024-10-31 01:52:53'),
        // (83, 'Pembangunan Awal Website INDOASPHALT.com', '\"[false,true,true,true,true,false,false,true,true,false,true,true,true,true,true,false,true,true,true,true,false,false,true,true,false,false,false,true,true,true,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:48:06', '2024-10-31 01:55:06'),
        // (84, 'Pemesanan dan Pemasangan Paket Berlangganan JWR+12 Mess MGR dengan ID PELANGGAN: 511912188 / 0266018946 | 30-09-2023 habis tempo, aktivasi ulang MNC Vision Rp 199.000 + admin Rp 5.000', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:48:39', '2024-10-31 01:55:43'),
        // (85, 'Pemasangan CCTV telah selesai dilakukan dengan konfigurasi IP address: 164 di area Timbangan', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 04:52:34', '2024-10-31 04:52:34'),
        // (86, 'Penerapan silicone sealant pada unit CCTV lama telah diperiksa dan dilakukan penanganan sesuai kebutuhan', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 04:53:01', '2024-10-31 04:53:01'),
        // (87, 'Pengecekan dan Perbaikan terhadap monitor CCTV di Pos Induk yang mengalami blank. Ditemukan bahwa Aplikasi SmartPSS melakukan reload otomatis, serta pengaturan pengguna (user) mengalami reset', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 04:53:36', '2024-10-31 04:53:36'),
        // (88, 'Adaptor monitor ASUS pada Komputer Asus milik Fathur terdeteksi mengalami kerusakan dan memerlukan penggantian', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:51:17', '2024-10-31 02:17:28'),
        // (89, 'Setting konfigurasi VPN PPTP & L2TP Laptop Pak Handry by Remote Anydesk', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:51:36', '2024-10-31 02:10:43'),
        // (90, 'Koneksi ping ke Jakarta terputus. Setelah ditelusuri, penyebabnya adalah router yang direstart oleh Pak Charles karena koneksi internet di Jakarta mengalami ketidakstabilan, dengan kondisi mati-hidup berulang kali.', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:51:53', '2024-10-31 02:11:09'),
        // (91, 'Telah dilakukan pengujian terhadap semua channel TV lokal setelah proses aktivasi ulang. Semua channel telah berhasil dibuka kembali dan berfungsi dengan baik.', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:52:12', '2024-10-31 02:11:31'),
        // (92, 'NVR pabrik mengalami gangguan (down). Setelah dilakukan pengecekan terhadap radiolink dari office ke Control Room menggunakan perintah CMD, hasilnya menunjukkan koneksi baik. Ternyata masalah terletak pada kabel LAN yang terhubung ke switch, sehingga dilakukan penggantian port. Setelah pergantian, sistem kembali normal, namun ditemukan satu port switch mengalami kerusakan.', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-01 05:52:51', '2024-10-31 02:12:03'),
        // (93, 'Dokumentasi Potret Foto dan Video Tamu dari Kementerian PUPR 10 Orang', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 05:53:52', '2024-10-31 02:12:25'),
        // (94, 'Persiapan sound system dan mikrofon untuk keperluan meeting direksi dengan karyawan Pukul 19.00 WITA telah dilakukan.', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 04:54:09', '2024-10-31 04:54:09'),
        // (95, 'Membuat dan Merancang Layout untuk Rencana Topologi jaringan baru menggunakan Starlink untuk dua lokasi, yaitu office dan pabrik. Kedua lokasi menggunakan dua router MikroTik yang terkoneksi langsung dengan jalur utama ke Jakarta. (Project Kedepan)', '\"[false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 05:55:10', '2024-10-31 02:14:58'),
        // (96, 'Telah dibangun topologi radiolink aktual untuk dibandingkan dengan topologi radiolink perencanaan. Topologi ini bertujuan mengubah jalur koneksi antara office dan pabrik, dan akan diajukan kepada Pak Kendro untuk pertimbangan lebih lanjut.', '\"[false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 05:55:25', '2024-10-31 02:19:46'),
        // (97, 'Telah melakukan panggilan kepada Pak Charles atas permintaan Pak Kendro untuk menanyakan lokasi pembelian perangkat Starlink beserta harga perangkat kerasnya', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 05:55:45', '2024-10-31 02:21:55'),
        // (98, 'Membuat Rancangan Design untuk Rencana Pemindahan Radiolink dari Workshop ke Samping Control Room telah selesai dibuat dan disetujui oleh Pak Kendro.', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 05:56:36', '2024-10-31 02:22:21'),
        // (99, 'Pemindahan Modem Starlink dari jaringan internet LNS bonding ke Jaringan Router KPA. Hujan sangat deras, jaringan mengalami down, hujan reda jaringan dikembalikan lagi ke mode bonding LNS.', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 04:54:31', '2024-10-31 04:54:31'),
        // (100, 'Telah mengaktifkan akun pengguna Tamu untuk keperluan Kementerian PUPR. Setelah selesai, akun tersebut dinonaktifkan kembali.', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 05:57:04', '2024-10-31 02:28:07'),
        // (101, 'Telah memberikan bantuan kepada Pak Umar terkait kendala dalam menggunakan aplikasi Skype untuk melakukan rapat', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-02 05:57:18', '2024-10-31 02:28:25'),
        // (102, 'Pemasangan CCTV dengan IP address 198 di area 201 telah selesai. Kabel LAN juga telah dicek dan dipastikan dalam kondisi sangat baik', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-03 04:55:07', '2024-10-31 04:55:07'),
        // (103, 'Access Point tidak memancarkan internet. Setelah dilakukan tes kabel menggunakan LAN tester, ditemukan bahwa kabel Orange dan Putih-Orange mengirim paket data terputus. Dilakukan crimping ulang, dan AP berfungsi kembali dengan baik.', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-03 05:58:11', '2024-10-31 02:32:20'),
        // (104, 'Telah memberikan pelayanan terhadap laptop pribadi Bu Hikmah yang mengeluhkan laptopnya lambat.', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-03 05:58:24', '2024-10-31 02:32:49'),
        // (105, 'Telah menerima telepon dari Pak Handri mengenai keluhan sistem Qube di kantor Jakarta yang beberapa kali mengalami gangguan (down). Setelah akan dilakukan remote ke site Jakarta, sistem kembali normal.', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-03 05:58:37', '2024-10-31 02:33:28'),
        // (106, 'Mengurus perijinan forklift beserta operatornya untuk membantu pekerjaan di ketinggian terkait pemasangan CCTV di area 201.', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-03 04:55:26', '2024-10-31 04:55:26'),
        // (107, 'Membuat User Hotspot baru atas nama : Suedi, Muhadi dan Zulhaidir (Pabrikasi)', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-03 04:55:49', '2024-10-31 04:55:49'),
        // (108, 'Training Komputer Excel Leader Baru Lokal Produksi (Pak Fathur & Pak Ode Amyn)', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-03 06:00:37', '2024-10-31 02:39:19'),
        // (109, 'Telah menerima telepon dari Pak Kendro mengenai perencanaan pembuatan tower jaringan radiolink di samping gedung DCS. Beliau menginformasikan adanya rencana pembangunan delapan tangki di sekitar kolam penampungan air dekat timbangan. Diminta agar rencana tersebut ditinjau ulang untuk memastikan bahwa tower yang akan dibangun tidak terhalang oleh tangki-tangki tersebut, sehingga jalur frekuensi tetap optimal.', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-04 06:04:14', '2024-10-31 02:39:52'),
        // (110, 'Permintaan Form Request Order Barang ke Administrasi Umum untuk Pemesanan Pembelian Konektor Penyambung LAN RJ-45 sebanyak 5 Pcs sesuai Permintaan dari Pak Jimmy, untuk Pemindahan Access Point dan Radiolink di Gerbang Utama ke Tiang Lampu di Area yang sama sekaligus Permintaan Order Konektor RJ-45 sebanyak 2 Pack.', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-04 06:07:56', '2024-10-31 02:40:29'),
        // (111, 'Pembongkaran dan Pelepasan Panel serta Kabel Jaringan di Panel Area 304, dikarenakan adanya pengerjaan pemindahan Limbah', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'CCTV serta Radiolink sementara tidak aktif karena di cabutnya semua port pada Switch didalam Panel', 'SETUJU', NULL, 1, 41, 10, '2024-10-04 06:09:48', '2024-10-31 02:40:50'),
        // (112, 'Membahas Perencanaan terkait Pembuatan Tower Jaringan baru di samping DCS bersama Pak Erta (Arsitek Sipil)', '\"[false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'Pembahasan terkait Tinggi Tangki dan Gedung Stockpile tidak terhalang dari Jarak Pandang diatas Tower serta Perancangan Rencana Design pada Tower Jaringan tersebut.', 'SETUJU', NULL, 1, 41, 10, '2024-10-04 06:12:37', '2024-10-31 02:41:22'),
        // (113, 'Monitoring CCTV, melakukan Rebooting pada Device CCTV yang tidak melakukan Response balik ketika di Ping', '\"[false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-05 06:13:34', '2024-10-31 02:41:57'),
        // (114, 'Informasi dari Pak Yuli (Kepala Bagian HK) Meminta Bantuan untuk Melakukan Pengecekkan CCTV, Playback Area Mess Karyawan pada Cam#4 Kamar No. 201 atas nama Firman Gustaman (KAI). Paket baju laundry telah hilang selama 5 hari sejak tanggal 2 Oktober 2024. Setelah ditelusuri oleh anggota Housekeeping (HK), tidak ditemukan catatan terkait laundry atas nama Firman Gustaman pada tanggal tersebut. Selain itu, catatan dari pihak laundry juga tidak menunjukkan adanya baju atas nama tersebut', '\"[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'sudah di temukan,  paket laundry di konfirmasi Pak Yuli ada di ruangan penghitungan Laundry', 'SETUJU', NULL, 1, 41, 10, '2024-10-07 06:16:17', '2024-10-31 02:42:42'),
        // (115, 'Telah diterima informasi dari Pak Hendri (Logistik) untuk memeriksa CCTV dan kabel LAN di area tersebut. Ditemukan bahwa tiang lampu tempat CCTV dan radiolink dalam kondisi miring setelah tertabrak forklift, dengan operator forklift adalah Pak Hendri sendiri. Setelah dilakukan pemeriksaan, kondisi CCTV, panel box, dan kabel dipastikan aman, namun tiang lampu mengalami kemiringan dan terdapat satu baut yang hilang', '\"[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-07 06:16:34', '2024-10-31 02:43:40'),
        // (116, 'Melakukan Riset terkait Penjual Paket Starlink Unlimited yang dapat di Beli Mati', '\"[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-07 06:17:24', '2024-10-31 02:48:07'),
        // (117, 'Melakukan Meeting untuk Pembahasan terkait Struktur Organisasi Baru.', '\"[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai dengan Struktur Organisasi yang baru.', 'SETUJU', NULL, 1, 41, 10, '2024-10-07 06:18:14', '2024-10-31 02:54:42'),
        // (118, 'Melakukan Pengecekan Tiang Selling Triangle RPX', '\"[false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai dengan melakukan pengukuran ulang disekitar tiang RPX', 'SETUJU', NULL, 1, 41, 10, '2024-10-08 06:19:13', '2024-10-31 02:54:15'),
        // (119, 'Traffic tinggi mengakibatkan jaringan melambat, telah di lakukan torch LAN dan didapat ada 2 kamera dengan kapasitas receive dan transmit yang tinggi. Sudah di reboot', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-08 06:19:33', '2024-10-31 02:53:46'),
        // (120, 'Pembuatan dan Perancangan Awal aplikasi Management Report untuk Optimalisasi Pelaporan.', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'membuat rancangan awal serta melakukan konfigurasi awal pada sistem aplikasi.', 'SETUJU', NULL, 1, 41, 10, '2024-10-08 06:21:09', '2024-10-31 02:53:15'),
        // (121, 'Telah melakukan panggilan dengan Pak Hendrik dari IT Suncity untuk menanyakan perihal paket data Starlink. Pak Hendrik menjelaskan bahwa Suncity memiliki satu perangkat Starlink yang saat ini tidak terpakai karena modem Starlink kurang optimal di perkotaan dan tidak mendukung penggunaan IP Publik dengan baik. Starlink menawarkan dua jenis layanan data: prioritas dan reguler. Suncity saat ini menggunakan layanan prioritas 40GB dengan layanan reguler unlimited. Beliau juga menyarankan untuk membeli langsung melalui website resmi Starlink agar dashboard bisa disetting sendiri, dibandingkan membeli dari reseller yang membatasi akses pengaturan.', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-08 06:21:24', '2024-10-31 02:52:48'),
        // (122, 'Pak Tri meminta bantuan untuk memberikan akses Wi-Fi kepada vendor mekanik alat berat Loader Sany, yang datang hari ini dari Kendari untuk melakukan servis loader. Konfirmasi sudah dilakukan dengan Bapak Laode Amyn.', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-08 06:21:49', '2024-10-31 02:51:48'),
        // (123, 'Mendapat informasi dari Pak Charles bahwa sewa Starlink LNS diperpanjang lagi selama 6 bulan. Selain itu, mendapat perintah dari Pak Kendro agar proyek pembangunan menara Starlink di DCS dipercepat. Informasi tersebut telah saya forward ke Pak Laode Amyn.', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-08 06:22:16', '2024-10-31 02:51:04'),
        // (124, 'Melakukan Koordinasi terkait Pembangunan Tower Jaringan Baru bersama Pak Suminta', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'Konfirmasi penentuan Titik pemasangan Bim Suku Besi yang akan menjadi Fondasi Menara Radiolink di samping gedung DCS.', 'SETUJU', NULL, 1, 41, 10, '2024-10-08 06:23:49', '2024-10-31 02:50:31'),
        // (125, 'Pak edi menanyakan mengenai, proyek menara radiolink di cat warna abu-abu dan meminta konfirmasi kerangka yang dibuat apakah sudah benar atau belum, sudah saya konfirmasi', '\"[false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-09 04:56:19', '2024-10-31 04:56:19'),
        // (126, 'Menemui pak suminta mengkonfirmasi proses menara sudah sampai mana, setelah di lokasi menara sudah 60% jadi. Kurang pagar pengaman, tangga dan proses pengecatan', '\"[false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-09 04:56:37', '2024-10-31 04:56:37'),
        // (127, 'Permintaan Pemasangan Unit UPS baru untuk Pak Erta (Arsitek Sipil)', '\"[false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 50, 'UPS sedang di perbaiki', 'SETUJU', NULL, 1, 41, 10, '2024-10-09 04:57:03', '2024-10-31 04:57:03'),
        // (128, 'Ukur lebar dan tinggi menara tower antena G6 di bukit, per 5 tahun sekali ganti kawat seling dan mengajukan saran untuk di lakukan pengecoran', '\"[false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-09 04:57:22', '2024-10-31 04:57:22'),
        // (129, 'Melakukan Presentasi terkait Progress pengerjaan Aplikasi Management Report ke Pak Andi (HRD)', '\"[false,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'Lanjut membangun Database untuk aplikasi.', 'SETUJU', NULL, 1, 41, 10, '2024-10-09 06:28:45', '2024-10-31 03:05:59'),
        // (130, 'Menemui Pak Sarfin di Area 304 dikonfirmasi pak sarfin memastikan lama pengerjaan limbah tidak dapat di prediksi untuk waktu selesai karena ditambah akan diteruskan ke proyek tangki 8. telah dikonfirmasi kepada Pak Amin dan Pak Andi terkait Non-aktif nya CCTV sementara waktu.', '\"[false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'CCTV dan Radiolink area 304 dan 305 P.Asphalt tidak dapat di aktifkan untuk beberapa waktu', 'SETUJU', NULL, 1, 41, 10, '2024-10-09 04:57:53', '2024-10-31 04:57:53'),
        // (131, 'Kamera CCTV di Area Timbangan Cam#1 dan Cam#4 mengalami RTO, dilakukan pengecekkan ke Lokasi.', '\"[false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'CCTV Cam#1 mengalami kerusakan pada Bagian Internal CCTV dan CCTV Cam#4 dilakukan Pembersihkan karena ada nya embun yang masuk.', 'SETUJU', NULL, 1, 41, 10, '2024-10-10 06:34:39', '2024-10-31 03:10:56'),
        // (132, 'Ambil HT HYT PD568 UL913 IS UHF 400-470MHz di Gudang untuk di tes perfomanya', '\"[false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false]\"', 100, 'Pengembalian HT Tersebut pada tanggal 27 Oktober', 'SETUJU', NULL, 1, 41, 10, '2024-10-10 06:35:23', '2024-10-31 03:11:40'),
        // (133, 'Penyelesaian Rangkaian Database serta membuat fungsi Update dan Delete untuk Tabel Laporan.', '\"[false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'Pengerjaan Progress Aplikasi Manajemen Report', 'SETUJU', NULL, 1, 41, 10, '2024-10-10 06:36:59', '2024-10-31 03:12:19'),
        // (134, 'Pak Wahyu (IT) telah melakukan pengecekan progress pembuatan tower di  bagian pabrikasi Pak Suminta', '\"[false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-10 06:37:34', '2024-10-31 03:12:56'),
        // (135, 'Evakuasi dua unit UPS di area 304 dan 305 P.Aspal telah dilakukan karena adanya pemindahan limbah dan proyek pembangunan tangki 8', '\"[false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-10 06:37:49', '2024-10-31 03:13:22'),
        // (136, 'Melakukan Riset terkait Rencana Pemesanan HT Untuk Produksi, pencarian spesifik pada standar Migas dan direkomendasikan untuk Menggunakan Motorola Seri XiR, Model terkhusus pada versi P6600i dan P6620i dilengkapi dengan fitur yang sesuai dengan kebutuhan industri, termasuk tahan debu dan air dengan sertifikasi IP67, serta memenuhi standar militer MIL-STD 810 untuk ketahanan terhadap kondisi ekstrim.', '\"[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'Rekomendasi telah diberikan kepada Pak Amin.', 'SETUJU', NULL, 1, 41, 10, '2024-10-11 04:58:48', '2024-10-31 04:58:48'),
        // (137, 'Melakukan Riset serta mempelajari Frekuensi HT yang optimal terkhusus pada TX dan RX nya yang performa nya stabil.', '\"[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-11 06:41:31', '2024-10-31 03:16:04'),
        // (138, 'Menyusun rencana pemindahan box panel CCTV 304 dari tiang lampu gerbang ke area pompa J2.', '\"[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'telah dikonfirmasi Pak Andi', 'SETUJU', NULL, 1, 41, 10, '2024-10-11 04:59:26', '2024-10-31 04:59:26'),
        // (139, 'Informasi dari Pak Edi (Translator), bahwa menara Tower Jaringan yang baru telah selesai dan akan di Bangun pada hari Minggu jam 07.00 WITA.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-12 06:43:40', '2024-10-31 03:17:15'),
        // (140, 'Konfirmasi penyelesaian Tower Jaringan Baru ke Pak Suminta serta Pak Didik terkait pemasangan pembangunan Tower di Area samping DCS.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-13 06:44:53', '2024-10-31 03:17:49'),
        // (141, 'Menginformasikan penundaan pemasangan kepada Pak Andi Translator agar diteruskan kepada TKA', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-13 06:45:14', '2024-10-31 03:18:23'),
        // (151, 'Penggaraman RO kantin & cleaning flowmeter', '\"[false,true,false,true,false,false,true,false,false,true,false,false,false,true,false,false,true,false,false,true,false,false,true,false,false,true,false,false,true,false,false,true]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-01 13:15:09', '2024-10-30 13:15:09'),
        // (152, 'Pemasangan preasur pompa 2', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-01 12:57:18', '2024-10-30 12:57:18'),
        // (153, 'Perbaikan toilet kamar 02 & 03 mes manager', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-01 12:57:28', '2024-10-30 12:57:28'),
        // (154, 'Perbaikan wastafel toilet umum mes manager', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-01 12:57:44', '2024-10-30 12:57:44'),
        // (155, 'Perbaikan pompa boster kantin', '\"[false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-01 12:57:57', '2024-10-30 12:57:57'),
        // (156, 'Pemasangan U-bolt pipa area jembatan', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-02 12:57:01', '2024-10-30 12:57:01'),
        // (157, 'Cleaning lampu lalat', '\"[false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-02 13:38:02', '2024-10-30 13:38:02'),
        // (158, 'Perbaikan AC ruang makan DCS', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-02 13:03:21', '2024-10-30 13:03:21'),
        // (159, 'Penggantian pompa boster kantin', '\"[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-02 13:08:50', '2024-10-30 13:08:50'),
        // (160, 'Pengecatan pipa air area jembatan sampai mesin pompa sungai', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-03 13:10:42', '2024-10-30 13:10:42'),
        // (161, 'Perbaikan lampu lalat', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-03 13:12:24', '2024-10-30 13:12:24'),
        // (162, 'Perbaikan wastafel kantin cina', '\"[false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-03 13:13:04', '2024-10-30 13:13:04'),
        // (163, 'Perbaikan handshower toilet kamar no.06 & toilet umum mes manager', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-04 13:16:53', '2024-10-30 13:16:53'),
        // (164, 'Penggantian filter RO mes karyawan', '\"[false,false,false,false,true,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,true,false,false,true,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-04 13:19:31', '2024-10-30 13:19:31'),
        // (165, 'Penggaraman RO mes karyawan & cleaning flowmeter', '\"[false,false,false,false,true,false,false,true,false,false,true,false,false,false,true,false,false,false,true,false,false,false,false,true,false,false,false,true,false,false,false,true]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-04 13:21:47', '2024-10-30 13:21:47'),
        // (166, 'Perbaikan closet toilet umum mes karyawan', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-04 13:22:29', '2024-10-30 13:22:29'),
        // (167, 'penyiraman jalan area pabrik', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-04 13:23:35', '2024-10-30 13:23:35'),
        // (168, 'Perbaikan AC standing office', '\"[false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-04 13:24:07', '2024-10-30 13:24:07'),
        // (169, 'Perbaikan jalur pipa air jembatan', '\"[false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-05 13:26:51', '2024-10-30 13:26:51'),
        // (170, 'Perbaikan orinal mes karyawan 1 unit', '\"[false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-05 13:27:31', '2024-10-30 13:27:31'),
        // (171, 'Perbaikan kelistrikan kantin (ganti MCB) & Perbaikan kabel kulkas daffa', '\"[false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-06 13:28:33', '2024-10-30 13:28:33'),
        // (172, 'Perbaikan pemanas nasi kantin cina', '\"[false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-06 13:30:13', '2024-10-30 13:30:13'),
        // (173, 'Cleaning saluran air & bak control kantin', '\"[false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-06 13:31:41', '2024-10-30 13:31:41');
        // INSERT INTO `laporan` (`id`, `laporan_rencana_kerja`, `laporan_jumlah_hari`, `laporan_presentasi_pencapaian`, `laporan_keterangan`, `laporan_status`, `divisi_id`, `login_id`, `periode_id`, `created_at`, `updated_at`) VALUES
        // (174, 'Perbaikan pintu kamar mandi kantin 1 unit (Pemasangan kunci slot)', '\"[false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-06 13:32:43', '2024-10-30 13:32:43'),
        // (175, 'Cleaning mesin RO mes karyawan & ganti filter 1 pcs', '\"[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-07 13:36:22', '2024-10-30 13:36:22'),
        // (176, 'Cleaning mesin RO kantin & penggantian filter 1 pcs', '\"[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-07 13:37:07', '2024-10-30 13:37:07'),
        // (177, 'Plassing saluran air kamar no.06 mes manager', '\"[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-07 13:38:57', '2024-10-30 13:38:57'),
        // (178, 'Pemotongan dan pemasangan pipa air untuk area depan wokshop alat berat', '\"[false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-07 13:40:06', '2024-10-30 13:40:06'),
        // (179, 'Perbaikan closet mes karyawan 2 unit', '\"[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-07 13:40:39', '2024-10-30 13:40:39'),
        // (180, 'Senai pipa air untuk pemasangan depan workshop alat berat', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-08 13:41:45', '2024-10-30 13:41:45'),
        // (181, 'Perbaikan AC lab bawah', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-08 13:42:12', '2024-10-30 13:42:12'),
        // (182, 'Pembuatan laporan bulan september 2024', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-08 13:43:06', '2024-10-30 13:43:06'),
        // (183, 'Perbaikan closet kantin', '\"[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'PENDING', NULL, 19, 42, 10, '2024-10-08 13:44:17', '2024-10-30 13:44:17'),
        // (184, 'Memantau proyek pemasangan menara tower jaringan.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-14 15:36:36', '2024-10-31 03:18:45'),
        // (185, 'Menambah jalur selebar 60-80 cm di samping menara tower jaringan dan koordinasi dengan Pak Frans permintaan penambahan Plat untuk jalur  jalan samping menara lebar 60-80 cm', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'progress lanjutan Koordinasi dengan Pak Ujang permintaan PHL untuk pengecatan jalur  jalan tambahan', 'SETUJU', NULL, 1, 41, 10, '2024-10-14 15:37:46', '2024-10-31 03:19:20'),
        // (186, 'Koordinasi dengan Pak Rukman terkait permintaan penarikan kabel  power ke atas menara dan pemindahan power dari tiang lampu 304 ke area pompa J2', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-14 15:38:20', '2024-10-31 03:19:58'),
        // (187, 'Mengirim laporan invoice Zoom meeting periode 13 Oktober - 13  November 2024 atas permintaan Pak Handry', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-14 15:38:46', '2024-10-31 03:20:31'),
        // (188, 'Monitor CCTV di pos induk mati pada 2 lokasi (Gate 1 #cam2 dan Pos 2  gerbang) telah dikondisikan', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-14 15:39:09', '2024-10-31 03:21:06'),
        // (189, 'Pembuatan Interfaces untuk Halaman Index Laporan pada Aplikasi Manajemen Report', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-14 15:39:45', '2024-10-31 03:21:33'),
        // (190, 'Playback CCTV Stockpile untuk insiden truk terbalik Pukul 7.44 WITA', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-14 05:00:05', '2024-10-31 05:00:05'),
        // (191, 'Pemasangan 2 Kabel Belden UTP Cat 6 dan crimping Connector RJ-45 untuk Jalur Radiolink dan Jalur extensi tambahan untuk penggunaan Radio Tambahan pada Tower Baru', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-15 05:00:52', '2024-10-31 05:00:52'),
        // (192, 'Setting share folder HSE di laptop Pak Anang atas permintaan Pak Jarot, Bookmark Login Hotspot di laptop Pak Anang dan memenuhi permintaan Pak Sudarman terkait rekaman insiden truk sebelum terbalik dan di saat berdiri kembali serta melakukan Koordinasi dengan Pak Frans/Pak Suminta/Pak Didik perihal pembuatan support/dudukan box panel di area pompa jitu', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-15 15:42:17', '2024-10-31 03:31:38'),
        // (193, 'Pendampingan & Dokumentasi pihak kalibrasi timbangan serta Pembukaan akses user Tamu untuk kebutuhan Tamu dari Kalibrasi', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-15 15:42:54', '2024-10-31 03:32:09'),
        // (194, 'Mengurus perijinan/permit pekerjaan berbahaya dan ketinggian di kantor HSE dan melanjutkan permintaan email perusahaan atas nama Anang Nugroho ke Pak Laode Amyn', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-15 05:01:13', '2024-10-31 05:01:13'),
        // (195, 'Muncul tampilan notife error \"Maximum User Sudah Tercapai (10 User),Menutup Aplikasi!\" di aplikasi Qube Sistem Admin Gudang atas nama Bu Hesti,  sudah di forward ke Pak Handry HO Jakarta', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'Dilakukan Update 1 folder Qube System User Hesti atas permintaan Pak Handry', 'SETUJU', NULL, 1, 41, 10, '2024-10-15 05:01:42', '2024-10-31 05:01:42'),
        // (196, 'Pembongkaran box panel di area 304 dan Pencopotan 2 unit CCTV, 1 radiolink client, dan kabel LAN 4 line dan akan dipindah ke Area Pompa J2', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'Koordinasi dengan Pak Ruqman terkait pelaksanaan penarikan kabel power dari panel induk 24 jam di area pompa J2 sepanjang 10 meter menuju box panel', 'SETUJU', NULL, 1, 41, 10, '2024-10-16 05:02:44', '2024-10-31 05:02:44'),
        // (197, 'Pemasangan box panel di area pompa J2, Penarikan kabel power oleh tim elektrik (Pak Heriyana dan Pak Safrin) untuk kebutuhan CCTV dan radiolink client dan Penarikan kabel LAN CCTV 304 #cam1 dan #cam2 dipindahkan ke area  pompa J2', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-16 15:44:59', '2024-10-31 03:38:57'),
        // (198, 'Pembongkaran box panel radio repeater destilasi dan pencabutan  power oleh tim elektrik', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-16 15:45:16', '2024-10-31 03:42:56'),
        // (199, 'Pengambilan kabel listrik NYM 3 x 2,5 di gudang untuk power listrik panel menara radiolink repeater', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-16 05:03:00', '2024-10-31 05:03:00'),
        // (200, 'Pak Anang meminta penambahan setting share folder Pak Jarot di laptopnya', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-16 15:45:57', '2024-10-31 03:45:15'),
        // (201, 'Mendapat informasi kepada Pak Rukman bahwa penarikan kabel  menara dipending karena tim elektrik sedang dikejar untuk penyelesaian power di RO Pabrik.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-16 15:46:19', '2024-10-31 03:46:21'),
        // (202, 'Playback rekaman CCTV area packaging terkait insiden kecelakaan karyawan yang kakinya terkena aspal panas,  atas permintaan Pak Jarot', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-16 05:03:29', '2024-10-31 05:03:29'),
        // (203, 'CCTV Timbangan 2 unit mati dikarenakan ada kerusakan pada Internal CCTV serta pengecekkan CCTV Mati pada area Workshop', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'CCTV Workshop 1 unit mati (Kamera lama)', 'SETUJU', NULL, 1, 41, 10, '2024-10-17 15:47:34', '2024-10-31 03:48:08'),
        // (204, 'Reboot CCTV Pabrik#cam2 serta melakukan bantuan terkait pencarian software HT Motorola CP210 punya pribadi Pak Aan', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-17 15:48:16', '2024-10-31 03:48:39'),
        // (205, 'Pantau Penarikan Kabel Listrik dari panel di bawah Destilasi sampai  dengan atas menara Jaringan (Pak Heriyana, Pak Amin & Pak Tio dari Electric) dan melakukan pembongkaran Kabel Listrik Jaringan dari Destilasi Lantai 3 sampai dasar', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-18 05:03:48', '2024-10-31 05:03:48'),
        // (206, 'Penarikan Kabel LAN dari  ControlRoom Lt.2 sampai bagian atas menara serta pemasangan box panel, UPS & Switch Hub', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-18 05:04:29', '2024-10-31 05:04:29'),
        // (207, 'Mempersiapkan Perlengkapan dan Zoom Meeting Konsultan', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-18 05:04:52', '2024-10-31 05:04:52'),
        // (208, 'Connect Kabel listrik dipanel induk destilasi (Pak Heriyana & Pak Abi)', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-18 15:50:35', '2024-10-31 03:52:36'),
        // (209, 'Bug Fixing dan Testing Fitur halaman Index Laporan serta menambahkan Fungsi Update Data Persiapan untuk testing data Uji pada Aplikasi Management Report', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-19 15:51:37', '2024-10-31 03:53:14'),
        // (210, 'Membantu Setting HT Pribadi milik Pak Wiji, HT BAOFENG Tipe UV-82 dan dilanjut dengan mengerjakan Bug Fixing pada Aplikasi Manajemen Report terkait Proses update Laporan pada Modal Aplikasi Management Report', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-21 15:52:33', '2024-10-31 04:03:33'),
        // (211, 'Memindahkan Access Point WiFi dari panel di bawah Tower Jaringan  ke dalam Ruangan Pak Sudarman di ControlRoom Lt.1', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false]\"', 60, 'Belum selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-21 05:05:25', '2024-10-31 05:05:25'),
        // (212, 'Bug Fixing Aplikasi Manajemen Report (Perbaikan error pada halaman   login ketika salah memasukkan pasword)', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-21 15:53:28', '2024-10-31 04:13:00'),
        // (213, 'Pengecekan Sudut Pandang lurus antar Radio Office dan Pabrik  memastikan tidak ada halangan dan Melanjutkan Pembangunan Web Indoasphalt', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-23 15:54:06', '2024-10-31 04:14:14'),
        // (214, 'Lepas Radiolink Repeater Client di Tiang Workshop serta Pasang Radiolink Repeater Client di Menara Jaringan DCS, Connect to Switch Server ControlRoom, Tes Perfoma dengan Speedtest.com dan Tes Ping 8.8.8.8 dan detik.com dan Periksa keadaan Kabel LAN Radio Pabrik dan Office', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-24 05:06:27', '2024-10-31 05:06:27'),
        // (215, 'Atur Rotasi kemiringan Radiolink Repeater Office to Pabrik dilanjut dengan Tes speed sebelum dan sesudah jaringan di (Lab, Gudang, ControlRoom Lt.1dan ControlRoom Lt.2)', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-24 05:06:45', '2024-10-31 05:06:45'),
        // (216, 'Tes panggilan dari pabrik ke luar (Yogyakarta & Makassar) suara jernih tanpa putus setelah melakukan pengecekkan bandwith dari radio repeater pabrik ke office', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-24 05:07:05', '2024-10-31 05:07:05'),
        // (217, 'Dapat laporan bahwa pak sudarman ketika telepone dengan direksi di Jakarta masih sering putus-putus, dilanjut dengan Konfirmasi titik ketika menerima telepone, titik berada di area Mixer.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false]\"', 100, 'Cek ke lokasi Mixer, Area dengan sinyal yang lemah karena jauh dari Access Point dan banyak tangki besi yang menghalangi', 'SETUJU', NULL, 1, 41, 10, '2024-10-25 05:07:37', '2024-10-31 05:07:37'),
        // (218, 'Bantu TKA a.n Sunhe lupa akun Masuk dashboard Orbit, Bantu Setting HT Pribadi Punya Pak Sofiyan serta Setting Ruang Meeting untuk Rapat dengan Jakarta', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-25 15:57:45', '2024-10-31 04:27:40'),
        // (219, 'Pemindahan 2 Unit CCTV 304, UPS, Switch Hub dan Radiolink Repeater ke Pompa J2, Penarikan Kabel 3 Line langsung connect.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-29 05:08:17', '2024-10-31 05:08:17'),
        // (220, 'Pasang Radio Repeater di Tower Jaringan DCS mengarah ke Pompa J2 1 Unit, Connect Switch Hub dan UPS.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false]\"', 100, 'selesai, sekaligus membantu Pak Anang untuk Download Video dari Youtube untuk Tutorial Pemasangan Tali Helm Safety.', 'SETUJU', NULL, 1, 41, 10, '2024-10-29 05:08:41', '2024-10-31 05:08:41'),
        // (221, 'Melakukan Koordinasi bersama divisi Electrical & Instrumen, diinfokan bahwa ada agenda Pencabutan semua tiang listrik satu jalur samping kolam area 305, CCTV 3 Unit, Switch Hub, UPS dan Radiolink Repeater di Bongkar.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false]\"', 100, 'sementara CCTV 305 P.Asphalt akan dimatikan dalam beberapa waktu yang belum dapat ditentukan, terkait pembangunan Area untuk Packaging baru pada area tersebut.', 'SETUJU', NULL, 1, 41, 10, '2024-10-29 05:10:03', '2024-10-31 05:10:03'),
        // (222, 'Melakukan Perbaikan sekaligus Cleaning Catridge Tinta dari Printer di Control Room Lt.2', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false]\"', 100, 'Hasil print kurang baik, dilakukan pengecekkan langsung dan di bersihkan sehingga dapat kembali jernih hasil printnya.', 'SETUJU', NULL, 1, 41, 10, '2024-10-29 00:26:46', '2024-10-31 04:30:59'),
        // (223, 'Pengembalian HT HYT PD-568 yang sebelumnya di pinjam untuk keperluan pengetesan konfigurasi.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false]\"', 100, 'telah diterima oleh pak Rizaldin (Warehouse).', 'SETUJU', NULL, 1, 41, 10, '2024-10-29 00:27:51', '2024-10-31 04:31:32'),
        // (224, 'Melakukan Reboot CCTV di beberapa Area : Gudang Gas, Tiang Pabrik cam#2, Crusher Cam#1 dan Cam#5, Stockpile baru Cam#1', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false]\"', 100, 'setelah di Reboot, kamera berjalan dengan normal kembali.', 'SETUJU', NULL, 1, 41, 10, '2024-10-29 00:29:15', '2024-10-31 04:32:06'),
        // (225, 'Dokumentasi Foto dan Video untuk kebutuhan Dokumentasi Proses Packaging di 305, Pengambilan Foto Karung Asphalt baru Indoasphalt PG-70 dan PG-76', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-30 05:11:00', '2024-10-31 05:11:00'),
        // (226, 'Radio dan CCTV Area 304 Mati', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false]\"', 100, 'UPS rusak, banyak terdapat semut merah. Ganti UPS. Selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-30 05:11:23', '2024-10-31 05:11:23'),
        // (227, 'Ganti Battery Aki UPS Sebanyak 4 Unit untuk 2 UPS.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-30 05:10:25', '2024-10-31 05:10:25'),
        // (228, 'Running dan Penyelesaian Konfigurasi HT Merk WLN Milik pribadi Pak Sofyan (Produksi)', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false]\"', 100, 'selesai', 'SETUJU', NULL, 1, 41, 10, '2024-10-30 00:37:49', '2024-10-31 04:38:25'),
        // (232, 'Reset Counter Pemakaian Bulanan Kuota User, Mangle, Interfaces dan Queues-Tree pada Jaringan MikroTik Ecoasphalt', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 0, 'progress', 'PENDING', NULL, 1, 41, 11, '2024-11-01 02:31:12', '2024-10-31 02:31:12'),
        // (233, 'Dokumentasi Foto dan Video untuk Tamu dari Kementrian Perindustrian.', '\"[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 0, 'progress', 'PENDING', NULL, 1, 41, 11, '2024-11-01 02:30:59', '2024-10-31 02:30:59'),
        // (234, 'Pengecekkan Rutin CCTV Area Office dan Pabrik', '\"[false,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false]\"', 100, 'selesai', 'PENDING', NULL, 1, 41, 11, '2024-11-01 02:32:52', '2024-10-31 02:32:52'),
        // (235, 'Pengerjaan Penarikan Kabel sambungan baru di Area Gerbang 1 (Gerbang Depan) terkait pemindahan Posisi Radiolink Repeater dan Access Point ke Titik Lain di area tersebut.', '\"[false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 0, 'digunakan 2 konektor sambungan untuk tipe RJ-45', 'PENDING', NULL, 1, 41, 11, '2024-11-04 04:51:21', '2024-10-31 04:51:21'),
        // (248, 'Topik hangat yang menjadi konsen di safety', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:44:20', '2024-10-31 03:44:20'),
        // (249, 'Pembuatan rambu safety area kerja pabrik dan area lainnya', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:44:50', '2024-10-31 03:44:50'),
        // (250, 'Penanganan karyawan yang sakit ketika bekerja sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:45:06', '2024-10-31 03:45:06'),
        // (251, 'Penanganan karyawan yang mengalami kecelakaan kerja ketika bekerja sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:45:20', '2024-10-31 03:45:20'),
        // (252, 'Pengawasan dan penerbitan ijin kerja kertinggian sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:46:24', '2024-10-31 03:46:24'),
        // (253, 'Pengawasan dan penerbitan ijin kerja panas sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:46:56', '2024-10-31 03:46:56'),
        // (254, 'Pengawasan dan penerbitan ijin kerja Lifting Crane sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:47:45', '2024-10-31 03:47:45'),
        // (255, 'Pengawasan dan penerbitan ijin kerja Ruang Terbatas sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:48:11', '2024-10-31 03:48:11'),
        // (256, 'Pengawasan dan penerbitan ijin kerja Galian Tanah sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:48:47', '2024-10-31 03:48:47'),
        // (257, 'Pengawasan dan penerbitan ijin kerja Konstruksi sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:50:21', '2024-10-31 03:50:21'),
        // (258, 'Training safety induction sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:51:42', '2024-10-31 03:51:42'),
        // (259, 'Penyusunan matery training', NULL, 0, 'Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:54:15', '2024-10-31 03:54:15'),
        // (260, 'Penyusunan Rintek dan Pertek untuk Lingkungan', NULL, 0, 'Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:55:03', '2024-10-31 03:55:03'),
        // (261, 'Penyiraman area jalan yang berdebu', NULL, 0, 'Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-01 03:57:52', '2024-10-31 03:57:52'),
        // (262, 'Pemindahan Radiolink Repeater di Area Gudang dan Workshop ke Menara Tower Jaringan Baru.', '\"[false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 0, '1 Unit Radiolink dari Gudang, 2 Unit Radiolink di Workshop.', 'PENDING', NULL, 1, 41, 11, '2024-11-07 04:53:22', '2024-10-31 04:53:22'),
        // (263, 'Pengaturan Konfigurasi Ulang pada Radiolink Repeater Area Tiang Hydrant', '\"[false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 0, 'Pergantian Channel dan IP sesuai kebutuhan untuk penyambungan jalur baru pada Jaringan.', 'PENDING', NULL, 1, 41, 11, '2024-11-07 04:53:38', '2024-10-31 04:53:38'),
        // (264, 'Pengecekkan dan Inspeksi Data dari Aplikasi Timbangan.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 100, 'progress', 'PENDING', NULL, 1, 41, 11, '2024-11-18 04:54:54', '2024-10-31 04:54:54'),
        // (265, 'Ganti Radio Ubiquiti PBE-5AC-620 Power Beam di Control Room yang mengarah pada Tiang Lampu depan Workshop.', '\"[false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 0, 'diganti dengan 2 Unit Radiolink.', 'PENDING', NULL, 1, 41, 11, '2024-11-11 04:56:29', '2024-10-31 04:56:29'),
        // (266, 'Konfigurasi 2 Unit Radio baru untuk menggantikan Radio yang ada di Control Room yang mengarah ke Tiang Lampu Workshop.', '\"[false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 0, 'Konfigurasi Radio NSMS NanoStation MS.', 'PENDING', NULL, 1, 41, 11, '2024-11-11 04:57:30', '2024-10-31 04:57:30'),
        // (267, 'Penarikan Kabel Belden LAN RJ-45 untuk Access Point di Area Mixer, Konfigurasi Access Point dan Connect ke Switch Hub yang ada di Server NVR pada Control Room Lt.2', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false]\"', 0, 'progress', 'PENDING', NULL, 1, 41, 11, '2024-11-28 04:59:25', '2024-10-31 04:59:25'),
        // (268, 'Pembuatan Pembaharuan Topologi Jaringan Pabrik dan Office.', '\"[false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]\"', 0, 'menunggu pergantian Radio pada Control Room ke Workshop', 'PENDING', NULL, 1, 41, 10, '2024-10-14 05:00:11', '2024-10-31 05:00:11'),
        // (269, 'Topik hangat yang menjadi konsen di safety', NULL, 0, 'Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:14:45', '2024-10-31 05:14:45'),
        // (270, 'Pembuatan rambu safety area kerja pabrik dan area lainnya', NULL, 0, 'Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:15:47', '2024-10-31 05:15:47'),
        // (271, 'Penanganan karyawan yang sakit ketika bekerja sebanyak', NULL, 0, 'Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:16:07', '2024-10-31 05:16:07'),
        // (272, 'Penanganan karyawan yang mengalami kecelakaan kerja ketika bekerja sebanyak', NULL, 0, 'Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:16:32', '2024-10-31 05:16:33'),
        // (273, 'Pengawasan dan penerbitan ijin kerja kertinggian sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:16:54', '2024-10-31 05:16:54'),
        // (274, 'Pengawasan dan penerbitan ijin kerja panas sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:17:19', '2024-10-31 05:17:19'),
        // (275, 'Pengawasan dan penerbitan ijin kerja Lifting Crane sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:18:18', '2024-10-31 05:18:18'),
        // (276, 'Pengawasan dan penerbitan ijin kerja Ruang Terbatas sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:20:09', '2024-10-31 05:20:09'),
        // (277, 'Pengawasan dan penerbitan ijin kerja Galian Tanah sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:22:41', '2024-10-31 05:22:41'),
        // (278, 'Pengawasan dan penerbitan ijin kerja Konstruksi sebanyak', NULL, 0, 'Pekerjaan Rutin', 'PENDING', NULL, 17, 39, 11, '2024-11-09 05:23:03', '2024-10-31 05:23:03');
        //         ");
    }
}
